// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v3

import (
	hyrulekingdom "github.com/pwittrock/apiserver-helloworld/pkg/apis/hyrulekingdom"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v3_ZeldasCastle_To_hyrulekingdom_ZeldasCastle,
		Convert_hyrulekingdom_ZeldasCastle_To_v3_ZeldasCastle,
		Convert_v3_ZeldasCastleList_To_hyrulekingdom_ZeldasCastleList,
		Convert_hyrulekingdom_ZeldasCastleList_To_v3_ZeldasCastleList,
		Convert_v3_ZeldasCastleSpec_To_hyrulekingdom_ZeldasCastleSpec,
		Convert_hyrulekingdom_ZeldasCastleSpec_To_v3_ZeldasCastleSpec,
		Convert_v3_ZeldasCastleStatus_To_hyrulekingdom_ZeldasCastleStatus,
		Convert_hyrulekingdom_ZeldasCastleStatus_To_v3_ZeldasCastleStatus,
	)
}

func autoConvert_v3_ZeldasCastle_To_hyrulekingdom_ZeldasCastle(in *ZeldasCastle, out *hyrulekingdom.ZeldasCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v3_ZeldasCastleSpec_To_hyrulekingdom_ZeldasCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v3_ZeldasCastleStatus_To_hyrulekingdom_ZeldasCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_v3_ZeldasCastle_To_hyrulekingdom_ZeldasCastle(in *ZeldasCastle, out *hyrulekingdom.ZeldasCastle, s conversion.Scope) error {
	return autoConvert_v3_ZeldasCastle_To_hyrulekingdom_ZeldasCastle(in, out, s)
}

func autoConvert_hyrulekingdom_ZeldasCastle_To_v3_ZeldasCastle(in *hyrulekingdom.ZeldasCastle, out *ZeldasCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_hyrulekingdom_ZeldasCastleSpec_To_v3_ZeldasCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_hyrulekingdom_ZeldasCastleStatus_To_v3_ZeldasCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_hyrulekingdom_ZeldasCastle_To_v3_ZeldasCastle(in *hyrulekingdom.ZeldasCastle, out *ZeldasCastle, s conversion.Scope) error {
	return autoConvert_hyrulekingdom_ZeldasCastle_To_v3_ZeldasCastle(in, out, s)
}

func autoConvert_v3_ZeldasCastleList_To_hyrulekingdom_ZeldasCastleList(in *ZeldasCastleList, out *hyrulekingdom.ZeldasCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]hyrulekingdom.ZeldasCastle)(unsafe.Pointer(&in.Items))
	return nil
}

func Convert_v3_ZeldasCastleList_To_hyrulekingdom_ZeldasCastleList(in *ZeldasCastleList, out *hyrulekingdom.ZeldasCastleList, s conversion.Scope) error {
	return autoConvert_v3_ZeldasCastleList_To_hyrulekingdom_ZeldasCastleList(in, out, s)
}

func autoConvert_hyrulekingdom_ZeldasCastleList_To_v3_ZeldasCastleList(in *hyrulekingdom.ZeldasCastleList, out *ZeldasCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ZeldasCastle)(unsafe.Pointer(&in.Items))
	return nil
}

func Convert_hyrulekingdom_ZeldasCastleList_To_v3_ZeldasCastleList(in *hyrulekingdom.ZeldasCastleList, out *ZeldasCastleList, s conversion.Scope) error {
	return autoConvert_hyrulekingdom_ZeldasCastleList_To_v3_ZeldasCastleList(in, out, s)
}

func autoConvert_v3_ZeldasCastleSpec_To_hyrulekingdom_ZeldasCastleSpec(in *ZeldasCastleSpec, out *hyrulekingdom.ZeldasCastleSpec, s conversion.Scope) error {
	out.Rupees = in.Rupees
	return nil
}

func Convert_v3_ZeldasCastleSpec_To_hyrulekingdom_ZeldasCastleSpec(in *ZeldasCastleSpec, out *hyrulekingdom.ZeldasCastleSpec, s conversion.Scope) error {
	return autoConvert_v3_ZeldasCastleSpec_To_hyrulekingdom_ZeldasCastleSpec(in, out, s)
}

func autoConvert_hyrulekingdom_ZeldasCastleSpec_To_v3_ZeldasCastleSpec(in *hyrulekingdom.ZeldasCastleSpec, out *ZeldasCastleSpec, s conversion.Scope) error {
	out.Rupees = in.Rupees
	return nil
}

func Convert_hyrulekingdom_ZeldasCastleSpec_To_v3_ZeldasCastleSpec(in *hyrulekingdom.ZeldasCastleSpec, out *ZeldasCastleSpec, s conversion.Scope) error {
	return autoConvert_hyrulekingdom_ZeldasCastleSpec_To_v3_ZeldasCastleSpec(in, out, s)
}

func autoConvert_v3_ZeldasCastleStatus_To_hyrulekingdom_ZeldasCastleStatus(in *ZeldasCastleStatus, out *hyrulekingdom.ZeldasCastleStatus, s conversion.Scope) error {
	out.Message = in.Message
	return nil
}

func Convert_v3_ZeldasCastleStatus_To_hyrulekingdom_ZeldasCastleStatus(in *ZeldasCastleStatus, out *hyrulekingdom.ZeldasCastleStatus, s conversion.Scope) error {
	return autoConvert_v3_ZeldasCastleStatus_To_hyrulekingdom_ZeldasCastleStatus(in, out, s)
}

func autoConvert_hyrulekingdom_ZeldasCastleStatus_To_v3_ZeldasCastleStatus(in *hyrulekingdom.ZeldasCastleStatus, out *ZeldasCastleStatus, s conversion.Scope) error {
	out.Message = in.Message
	return nil
}

func Convert_hyrulekingdom_ZeldasCastleStatus_To_v3_ZeldasCastleStatus(in *hyrulekingdom.ZeldasCastleStatus, out *ZeldasCastleStatus, s conversion.Scope) error {
	return autoConvert_hyrulekingdom_ZeldasCastleStatus_To_v3_ZeldasCastleStatus(in, out, s)
}
