/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by genwiring. Do not edit it manually!

package v3

import (
	"github.com/pwittrock/apiserver-helloworld/pkg/apis/hyrulekingdom"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apiserver-builder/pkg/builders"
)

var (
	ApiVersion = builders.NewVersionedApiBuilder("hyrulekingdom.k8s.io", "v3").WithResources(
		builders.NewVersionedResourceWithStorage( //  Resource endpoint
			hyrulekingdom.ZeldasCastleSingleton,
			func() runtime.Object { return &ZeldasCastle{} },     // Register versioned resource
			func() runtime.Object { return &ZeldasCastleList{} }, // Register versioned resource list
			&hyrulekingdom.ZeldasCastleStrategy{builders.StorageStrategySingleton},
		),
		builders.NewVersionedResourceWithStorage( // Resource status endpoint
			hyrulekingdom.ZeldasCastleStatusSingleton,
			func() runtime.Object { return &ZeldasCastle{} },     // Register versioned resource
			func() runtime.Object { return &ZeldasCastleList{} }, // Register versioned resource list
			&hyrulekingdom.ZeldasCastleStatusStrategy{builders.StatusStorageStrategySingleton},
		),
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

type ZeldasCastleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeldasCastle `json:"items"`
}
