// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package mushroomkingdom

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	builders "k8s.io/apiserver-builder/pkg/builders"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastle, InType: reflect.TypeOf(&PeachesCastle{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastleList, InType: reflect.TypeOf(&PeachesCastleList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastleSpec, InType: reflect.TypeOf(&PeachesCastleSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastleStatus, InType: reflect.TypeOf(&PeachesCastleStatus{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastleStatusStrategy, InType: reflect.TypeOf(&PeachesCastleStatusStrategy{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_PeachesCastleStrategy, InType: reflect.TypeOf(&PeachesCastleStrategy{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_ScaleCastle, InType: reflect.TypeOf(&ScaleCastle{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_mushroomkingdom_ScalePeachesCastleREST, InType: reflect.TypeOf(&ScalePeachesCastleREST{})},
	)
}

func DeepCopy_mushroomkingdom_PeachesCastle(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastle)
		out := out.(*PeachesCastle)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}

func DeepCopy_mushroomkingdom_PeachesCastleList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleList)
		out := out.(*PeachesCastleList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]PeachesCastle, len(*in))
			for i := range *in {
				if err := DeepCopy_mushroomkingdom_PeachesCastle(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

func DeepCopy_mushroomkingdom_PeachesCastleSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleSpec)
		out := out.(*PeachesCastleSpec)
		*out = *in
		return nil
	}
}

func DeepCopy_mushroomkingdom_PeachesCastleStatus(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleStatus)
		out := out.(*PeachesCastleStatus)
		*out = *in
		return nil
	}
}

func DeepCopy_mushroomkingdom_PeachesCastleStatusStrategy(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleStatusStrategy)
		out := out.(*PeachesCastleStatusStrategy)
		*out = *in
		if newVal, err := c.DeepCopy(&in.DefaultStatusStorageStrategy); err != nil {
			return err
		} else {
			out.DefaultStatusStorageStrategy = *newVal.(*builders.DefaultStatusStorageStrategy)
		}
		return nil
	}
}

func DeepCopy_mushroomkingdom_PeachesCastleStrategy(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleStrategy)
		out := out.(*PeachesCastleStrategy)
		*out = *in
		if newVal, err := c.DeepCopy(&in.DefaultStorageStrategy); err != nil {
			return err
		} else {
			out.DefaultStorageStrategy = *newVal.(*builders.DefaultStorageStrategy)
		}
		return nil
	}
}

func DeepCopy_mushroomkingdom_ScaleCastle(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ScaleCastle)
		out := out.(*ScaleCastle)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}

func DeepCopy_mushroomkingdom_ScalePeachesCastleREST(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ScalePeachesCastleREST)
		out := out.(*ScalePeachesCastleREST)
		*out = *in
		return nil
	}
}
