// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v2_PeachesCastle, InType: reflect.TypeOf(&PeachesCastle{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v2_PeachesCastleList, InType: reflect.TypeOf(&PeachesCastleList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v2_PeachesCastleSpec, InType: reflect.TypeOf(&PeachesCastleSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v2_PeachesCastleStatus, InType: reflect.TypeOf(&PeachesCastleStatus{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v2_ScaleCastle, InType: reflect.TypeOf(&ScaleCastle{})},
	)
}

func DeepCopy_v2_PeachesCastle(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastle)
		out := out.(*PeachesCastle)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}

func DeepCopy_v2_PeachesCastleList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleList)
		out := out.(*PeachesCastleList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]PeachesCastle, len(*in))
			for i := range *in {
				if err := DeepCopy_v2_PeachesCastle(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

func DeepCopy_v2_PeachesCastleSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleSpec)
		out := out.(*PeachesCastleSpec)
		*out = *in
		return nil
	}
}

func DeepCopy_v2_PeachesCastleStatus(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*PeachesCastleStatus)
		out := out.(*PeachesCastleStatus)
		*out = *in
		return nil
	}
}

func DeepCopy_v2_ScaleCastle(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ScaleCastle)
		out := out.(*ScaleCastle)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}
