// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v2

import (
	mushroomkingdom "github.com/pwittrock/apiserver-helloworld/apis/mushroomkingdom"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v2_PeachesCastle_To_mushroomkingdom_PeachesCastle,
		Convert_mushroomkingdom_PeachesCastle_To_v2_PeachesCastle,
		Convert_v2_PeachesCastleList_To_mushroomkingdom_PeachesCastleList,
		Convert_mushroomkingdom_PeachesCastleList_To_v2_PeachesCastleList,
		Convert_v2_PeachesCastleSpec_To_mushroomkingdom_PeachesCastleSpec,
		Convert_mushroomkingdom_PeachesCastleSpec_To_v2_PeachesCastleSpec,
		Convert_v2_PeachesCastleStatus_To_mushroomkingdom_PeachesCastleStatus,
		Convert_mushroomkingdom_PeachesCastleStatus_To_v2_PeachesCastleStatus,
		Convert_v2_ScaleCastle_To_mushroomkingdom_ScaleCastle,
		Convert_mushroomkingdom_ScaleCastle_To_v2_ScaleCastle,
	)
}

func autoConvert_v2_PeachesCastle_To_mushroomkingdom_PeachesCastle(in *PeachesCastle, out *mushroomkingdom.PeachesCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_PeachesCastleSpec_To_mushroomkingdom_PeachesCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v2_PeachesCastleStatus_To_mushroomkingdom_PeachesCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_v2_PeachesCastle_To_mushroomkingdom_PeachesCastle(in *PeachesCastle, out *mushroomkingdom.PeachesCastle, s conversion.Scope) error {
	return autoConvert_v2_PeachesCastle_To_mushroomkingdom_PeachesCastle(in, out, s)
}

func autoConvert_mushroomkingdom_PeachesCastle_To_v2_PeachesCastle(in *mushroomkingdom.PeachesCastle, out *PeachesCastle, s conversion.Scope) error {
	if err := Convert_mushroomkingdom_PeachesCastleSpec_To_v2_PeachesCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_mushroomkingdom_PeachesCastleStatus_To_v2_PeachesCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	out.ObjectMeta = in.ObjectMeta
	return nil
}

func Convert_mushroomkingdom_PeachesCastle_To_v2_PeachesCastle(in *mushroomkingdom.PeachesCastle, out *PeachesCastle, s conversion.Scope) error {
	return autoConvert_mushroomkingdom_PeachesCastle_To_v2_PeachesCastle(in, out, s)
}

func autoConvert_v2_PeachesCastleList_To_mushroomkingdom_PeachesCastleList(in *PeachesCastleList, out *mushroomkingdom.PeachesCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]mushroomkingdom.PeachesCastle, len(*in))
		for i := range *in {
			if err := Convert_v2_PeachesCastle_To_mushroomkingdom_PeachesCastle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func Convert_v2_PeachesCastleList_To_mushroomkingdom_PeachesCastleList(in *PeachesCastleList, out *mushroomkingdom.PeachesCastleList, s conversion.Scope) error {
	return autoConvert_v2_PeachesCastleList_To_mushroomkingdom_PeachesCastleList(in, out, s)
}

func autoConvert_mushroomkingdom_PeachesCastleList_To_v2_PeachesCastleList(in *mushroomkingdom.PeachesCastleList, out *PeachesCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PeachesCastle, len(*in))
		for i := range *in {
			if err := Convert_mushroomkingdom_PeachesCastle_To_v2_PeachesCastle(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func Convert_mushroomkingdom_PeachesCastleList_To_v2_PeachesCastleList(in *mushroomkingdom.PeachesCastleList, out *PeachesCastleList, s conversion.Scope) error {
	return autoConvert_mushroomkingdom_PeachesCastleList_To_v2_PeachesCastleList(in, out, s)
}

func autoConvert_v2_PeachesCastleSpec_To_mushroomkingdom_PeachesCastleSpec(in *PeachesCastleSpec, out *mushroomkingdom.PeachesCastleSpec, s conversion.Scope) error {
	out.Mushrooms = in.Mushrooms
	return nil
}

func Convert_v2_PeachesCastleSpec_To_mushroomkingdom_PeachesCastleSpec(in *PeachesCastleSpec, out *mushroomkingdom.PeachesCastleSpec, s conversion.Scope) error {
	return autoConvert_v2_PeachesCastleSpec_To_mushroomkingdom_PeachesCastleSpec(in, out, s)
}

func autoConvert_mushroomkingdom_PeachesCastleSpec_To_v2_PeachesCastleSpec(in *mushroomkingdom.PeachesCastleSpec, out *PeachesCastleSpec, s conversion.Scope) error {
	out.Mushrooms = in.Mushrooms
	return nil
}

func Convert_mushroomkingdom_PeachesCastleSpec_To_v2_PeachesCastleSpec(in *mushroomkingdom.PeachesCastleSpec, out *PeachesCastleSpec, s conversion.Scope) error {
	return autoConvert_mushroomkingdom_PeachesCastleSpec_To_v2_PeachesCastleSpec(in, out, s)
}

func autoConvert_v2_PeachesCastleStatus_To_mushroomkingdom_PeachesCastleStatus(in *PeachesCastleStatus, out *mushroomkingdom.PeachesCastleStatus, s conversion.Scope) error {
	return nil
}

func Convert_v2_PeachesCastleStatus_To_mushroomkingdom_PeachesCastleStatus(in *PeachesCastleStatus, out *mushroomkingdom.PeachesCastleStatus, s conversion.Scope) error {
	return autoConvert_v2_PeachesCastleStatus_To_mushroomkingdom_PeachesCastleStatus(in, out, s)
}

func autoConvert_mushroomkingdom_PeachesCastleStatus_To_v2_PeachesCastleStatus(in *mushroomkingdom.PeachesCastleStatus, out *PeachesCastleStatus, s conversion.Scope) error {
	return nil
}

func Convert_mushroomkingdom_PeachesCastleStatus_To_v2_PeachesCastleStatus(in *mushroomkingdom.PeachesCastleStatus, out *PeachesCastleStatus, s conversion.Scope) error {
	return autoConvert_mushroomkingdom_PeachesCastleStatus_To_v2_PeachesCastleStatus(in, out, s)
}

func autoConvert_v2_ScaleCastle_To_mushroomkingdom_ScaleCastle(in *ScaleCastle, out *mushroomkingdom.ScaleCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

func Convert_v2_ScaleCastle_To_mushroomkingdom_ScaleCastle(in *ScaleCastle, out *mushroomkingdom.ScaleCastle, s conversion.Scope) error {
	return autoConvert_v2_ScaleCastle_To_mushroomkingdom_ScaleCastle(in, out, s)
}

func autoConvert_mushroomkingdom_ScaleCastle_To_v2_ScaleCastle(in *mushroomkingdom.ScaleCastle, out *ScaleCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

func Convert_mushroomkingdom_ScaleCastle_To_v2_ScaleCastle(in *mushroomkingdom.ScaleCastle, out *ScaleCastle, s conversion.Scope) error {
	return autoConvert_mushroomkingdom_ScaleCastle_To_v2_ScaleCastle(in, out, s)
}
