// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	hyrule "github.com/pwittrock/apiserver-helloworld/apis/hyrule"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_HyruleCastle_To_hyrule_HyruleCastle,
		Convert_hyrule_HyruleCastle_To_v1_HyruleCastle,
		Convert_v1_HyruleCastleList_To_hyrule_HyruleCastleList,
		Convert_hyrule_HyruleCastleList_To_v1_HyruleCastleList,
		Convert_v1_HyruleCastleSpec_To_hyrule_HyruleCastleSpec,
		Convert_hyrule_HyruleCastleSpec_To_v1_HyruleCastleSpec,
		Convert_v1_HyruleCastleStatus_To_hyrule_HyruleCastleStatus,
		Convert_hyrule_HyruleCastleStatus_To_v1_HyruleCastleStatus,
	)
}

func autoConvert_v1_HyruleCastle_To_hyrule_HyruleCastle(in *HyruleCastle, out *hyrule.HyruleCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_HyruleCastleSpec_To_hyrule_HyruleCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_HyruleCastleStatus_To_hyrule_HyruleCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_v1_HyruleCastle_To_hyrule_HyruleCastle(in *HyruleCastle, out *hyrule.HyruleCastle, s conversion.Scope) error {
	return autoConvert_v1_HyruleCastle_To_hyrule_HyruleCastle(in, out, s)
}

func autoConvert_hyrule_HyruleCastle_To_v1_HyruleCastle(in *hyrule.HyruleCastle, out *HyruleCastle, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_hyrule_HyruleCastleSpec_To_v1_HyruleCastleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_hyrule_HyruleCastleStatus_To_v1_HyruleCastleStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_hyrule_HyruleCastle_To_v1_HyruleCastle(in *hyrule.HyruleCastle, out *HyruleCastle, s conversion.Scope) error {
	return autoConvert_hyrule_HyruleCastle_To_v1_HyruleCastle(in, out, s)
}

func autoConvert_v1_HyruleCastleList_To_hyrule_HyruleCastleList(in *HyruleCastleList, out *hyrule.HyruleCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]hyrule.HyruleCastle)(unsafe.Pointer(&in.Items))
	return nil
}

func Convert_v1_HyruleCastleList_To_hyrule_HyruleCastleList(in *HyruleCastleList, out *hyrule.HyruleCastleList, s conversion.Scope) error {
	return autoConvert_v1_HyruleCastleList_To_hyrule_HyruleCastleList(in, out, s)
}

func autoConvert_hyrule_HyruleCastleList_To_v1_HyruleCastleList(in *hyrule.HyruleCastleList, out *HyruleCastleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HyruleCastle)(unsafe.Pointer(&in.Items))
	return nil
}

func Convert_hyrule_HyruleCastleList_To_v1_HyruleCastleList(in *hyrule.HyruleCastleList, out *HyruleCastleList, s conversion.Scope) error {
	return autoConvert_hyrule_HyruleCastleList_To_v1_HyruleCastleList(in, out, s)
}

func autoConvert_v1_HyruleCastleSpec_To_hyrule_HyruleCastleSpec(in *HyruleCastleSpec, out *hyrule.HyruleCastleSpec, s conversion.Scope) error {
	out.Swords = in.Swords
	return nil
}

func Convert_v1_HyruleCastleSpec_To_hyrule_HyruleCastleSpec(in *HyruleCastleSpec, out *hyrule.HyruleCastleSpec, s conversion.Scope) error {
	return autoConvert_v1_HyruleCastleSpec_To_hyrule_HyruleCastleSpec(in, out, s)
}

func autoConvert_hyrule_HyruleCastleSpec_To_v1_HyruleCastleSpec(in *hyrule.HyruleCastleSpec, out *HyruleCastleSpec, s conversion.Scope) error {
	out.Swords = in.Swords
	return nil
}

func Convert_hyrule_HyruleCastleSpec_To_v1_HyruleCastleSpec(in *hyrule.HyruleCastleSpec, out *HyruleCastleSpec, s conversion.Scope) error {
	return autoConvert_hyrule_HyruleCastleSpec_To_v1_HyruleCastleSpec(in, out, s)
}

func autoConvert_v1_HyruleCastleStatus_To_hyrule_HyruleCastleStatus(in *HyruleCastleStatus, out *hyrule.HyruleCastleStatus, s conversion.Scope) error {
	out.SwordCount = in.SwordCount
	return nil
}

func Convert_v1_HyruleCastleStatus_To_hyrule_HyruleCastleStatus(in *HyruleCastleStatus, out *hyrule.HyruleCastleStatus, s conversion.Scope) error {
	return autoConvert_v1_HyruleCastleStatus_To_hyrule_HyruleCastleStatus(in, out, s)
}

func autoConvert_hyrule_HyruleCastleStatus_To_v1_HyruleCastleStatus(in *hyrule.HyruleCastleStatus, out *HyruleCastleStatus, s conversion.Scope) error {
	out.SwordCount = in.SwordCount
	return nil
}

func Convert_hyrule_HyruleCastleStatus_To_v1_HyruleCastleStatus(in *hyrule.HyruleCastleStatus, out *HyruleCastleStatus, s conversion.Scope) error {
	return autoConvert_hyrule_HyruleCastleStatus_To_v1_HyruleCastleStatus(in, out, s)
}
