/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by genwiring. Do not edit it manually!

package hyrulekingdom

import (
	"fmt"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver-builder/pkg/builders"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
	"k8s.io/client-go/pkg/api"
)

var (
	ZeldasCastleSingleton = builders.NewUnversionedResource(
		"zeldascastles",
		func() runtime.Object { return &ZeldasCastle{} },
		func() runtime.Object { return &ZeldasCastleList{} },
	)
	ZeldasCastleStatusSingleton = builders.NewUnversionedStatus(
		"zeldascastles",
		func() runtime.Object { return &ZeldasCastle{} },
		func() runtime.Object { return &ZeldasCastleList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewUnVersionedApiBuilder("hyrulekingdom.k8s.io").WithKinds(
		ZeldasCastleSingleton,
		ZeldasCastleStatusSingleton,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient=true

type ZeldasCastle struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   ZeldasCastleSpec
	Status ZeldasCastleStatus
}

// +genclient=true

type ZeldasCastleSpec struct {
	Rupees int
}

// +genclient=true

type ZeldasCastleStatus struct {
	Message string
}

//
// ZeldasCastle Functions and Structs
//
type ZeldasCastleStrategy struct {
	builders.DefaultStorageStrategy
}

type ZeldasCastleStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

type ZeldasCastleList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []ZeldasCastle
}

func (ZeldasCastle) NewStatus() interface{} {
	return ZeldasCastleStatus{}
}

func (pc *ZeldasCastle) GetStatus() interface{} {
	return pc.Status
}

func (pc *ZeldasCastle) SetStatus(s interface{}) {
	pc.Status = s.(ZeldasCastleStatus)
}

func (pc *ZeldasCastle) GetSpec() interface{} {
	return pc.Status
}

func (pc *ZeldasCastle) SetSpec(s interface{}) {
	pc.Spec = s.(ZeldasCastleSpec)
}

func (pc *ZeldasCastle) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *ZeldasCastle) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc ZeldasCastle) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store ZeldasCastle.
type ZeldasCastleRegistry interface {
	ListZeldasCastles(ctx request.Context, options *internalversion.ListOptions) (*ZeldasCastleList, error)
	GetZeldasCastle(ctx request.Context, id string, options *metav1.GetOptions) (*ZeldasCastle, error)
	CreateZeldasCastle(ctx request.Context, id *ZeldasCastle) (*ZeldasCastle, error)
	UpdateZeldasCastle(ctx request.Context, id *ZeldasCastle) (*ZeldasCastle, error)
	DeleteZeldasCastle(ctx request.Context, id string) error
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewZeldasCastleRegistry(s rest.StandardStorage) ZeldasCastleRegistry {
	return &storageZeldasCastle{s}
}

// Implement Registry
// storage puts strong typing around storage calls
type storageZeldasCastle struct {
	rest.StandardStorage
}

func (s *storageZeldasCastle) ListZeldasCastles(ctx request.Context, options *internalversion.ListOptions) (*ZeldasCastleList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	obj, err := s.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*ZeldasCastleList), err
}

func (s *storageZeldasCastle) GetZeldasCastle(ctx request.Context, id string, options *metav1.GetOptions) (*ZeldasCastle, error) {
	obj, err := s.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*ZeldasCastle), nil
}

func (s *storageZeldasCastle) CreateZeldasCastle(ctx request.Context, object *ZeldasCastle) (*ZeldasCastle, error) {
	obj, err := s.Create(ctx, object)
	if err != nil {
		return nil, err
	}
	return obj.(*ZeldasCastle), nil
}

func (s *storageZeldasCastle) UpdateZeldasCastle(ctx request.Context, object *ZeldasCastle) (*ZeldasCastle, error) {
	obj, _, err := s.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object, api.Scheme))
	if err != nil {
		return nil, err
	}
	return obj.(*ZeldasCastle), nil
}

func (s *storageZeldasCastle) DeleteZeldasCastle(ctx request.Context, id string) error {
	_, err := s.Delete(ctx, id, nil)
	return err
}
