/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

// ZeldasCastleListerExpansion allows custom methods to be added to
// ZeldasCastleLister.
type ZeldasCastleListerExpansion interface{}

// ZeldasCastleNamespaceListerExpansion allows custom methods to be added to
// ZeldasCastleNamespaeLister.
type ZeldasCastleNamespaceListerExpansion interface{}

// ZeldasCastleSpecListerExpansion allows custom methods to be added to
// ZeldasCastleSpecLister.
type ZeldasCastleSpecListerExpansion interface{}

// ZeldasCastleSpecNamespaceListerExpansion allows custom methods to be added to
// ZeldasCastleSpecNamespaeLister.
type ZeldasCastleSpecNamespaceListerExpansion interface{}

// ZeldasCastleStatusListerExpansion allows custom methods to be added to
// ZeldasCastleStatusLister.
type ZeldasCastleStatusListerExpansion interface{}

// ZeldasCastleStatusNamespaceListerExpansion allows custom methods to be added to
// ZeldasCastleStatusNamespaeLister.
type ZeldasCastleStatusNamespaceListerExpansion interface{}
