/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

// PeachesCastleListerExpansion allows custom methods to be added to
// PeachesCastleLister.
type PeachesCastleListerExpansion interface{}

// PeachesCastleNamespaceListerExpansion allows custom methods to be added to
// PeachesCastleNamespaeLister.
type PeachesCastleNamespaceListerExpansion interface{}

// PeachesCastleSpecListerExpansion allows custom methods to be added to
// PeachesCastleSpecLister.
type PeachesCastleSpecListerExpansion interface{}

// PeachesCastleSpecNamespaceListerExpansion allows custom methods to be added to
// PeachesCastleSpecNamespaeLister.
type PeachesCastleSpecNamespaceListerExpansion interface{}

// PeachesCastleStatusListerExpansion allows custom methods to be added to
// PeachesCastleStatusLister.
type PeachesCastleStatusListerExpansion interface{}

// PeachesCastleStatusNamespaceListerExpansion allows custom methods to be added to
// PeachesCastleStatusNamespaeLister.
type PeachesCastleStatusNamespaceListerExpansion interface{}

// ScaleCastleListerExpansion allows custom methods to be added to
// ScaleCastleLister.
type ScaleCastleListerExpansion interface{}

// ScaleCastleNamespaceListerExpansion allows custom methods to be added to
// ScaleCastleNamespaeLister.
type ScaleCastleNamespaceListerExpansion interface{}
