example_location: "examples"
api_groups:
  - "Wardle"
  - "MushroomKingdom"
resource_categories:
  - name: "MushroomKingdom Apis"
    include: "mushroomkingdom"
    resources:
    - name: PeachesCastle
      version: v2
      group: mushroomkingdom
  - name: "Hyrule Apis"
    include: "hyrule"
    resources:
    - name: HyruleCastle
      version: v1
      group: hyrule
