/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by genwiring. Do not edit it manually!

package hyrule

import (
	"fmt"
	metainternalversion "k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver-builder/pkg/defaults"
	genericapirequest "k8s.io/apiserver/pkg/endpoints/request"
	genericregistry "k8s.io/apiserver/pkg/registry/generic/registry"
	"k8s.io/apiserver/pkg/registry/rest"
	"k8s.io/client-go/pkg/api"
	"reflect"
)

var (
	// Package-wide variables from generator "zz_generated.api.register".
	registerFn = func(scheme *runtime.Scheme) error {
		scheme.AddKnownTypes(SchemeGroupVersion, &HyruleCastle{}, &HyruleCastleList{})
		metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
		return nil
	}

	SchemeGroupVersion = schema.GroupVersion{Group, runtime.APIVersionInternal}

	SchemeBuilder = runtime.NewSchemeBuilder(registerFn)

	AddToScheme = SchemeBuilder.AddToScheme
)

const (
	// Package-wide consts from generator "zz_generated.api.register".
	Group = "hyrule.k8s.io"
)

// +genclient=true

type HyruleCastle struct {
	Spec HyruleCastleSpec

	Status HyruleCastleStatus

	metav1.TypeMeta

	metav1.ObjectMeta
}

type HyruleCastleList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []HyruleCastle
}

type HyruleCastleSpec struct {
	Swords int
}

type HyruleCastleStatus struct {
	SwordCount int
}

///////////////////////////////////////////////////////////////////////////////
// HyruleCastle user functions //
///////////////////////////////////////////////////////////////////////////////

// Add functions to this type in order to override the default behaviors
type HyruleCastleStrategy struct {
	DefaultHyruleCastleStrategy
}

// Add functions to this type in order to override the default behaviors
type HyruleCastleStore struct {
	*genericregistry.Store
}

// Add functions to this type in order to override the default behaviors
type HyruleCastleStatusStore struct {
	*genericregistry.Store
}

// Registry is an interface for things that know how to store HyruleCastle.
type HyruleCastleRegistry interface {
	ListHyruleCastles(ctx genericapirequest.Context, options *metainternalversion.ListOptions) (*HyruleCastleList, error)
	GetHyruleCastle(ctx genericapirequest.Context, id string, options *metav1.GetOptions) (*HyruleCastle, error)
	CreateHyruleCastle(ctx genericapirequest.Context, id *HyruleCastle) (*HyruleCastle, error)
	UpdateHyruleCastle(ctx genericapirequest.Context, id *HyruleCastle) (*HyruleCastle, error)
	DeleteHyruleCastle(ctx genericapirequest.Context, id string) error
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewHyruleCastleRegistry(s rest.StandardStorage) HyruleCastleRegistry {
	return &storageHyruleCastle{s}
}

///////////////////////////////////////////////////////////////////////////////
// HyruleCastle System functions //
///////////////////////////////////////////////////////////////////////////////

// Use the override strategy and embedd the defaults for anything not override.
var HyruleCastleStrategySingleton = &HyruleCastleStrategy{
	DefaultHyruleCastleStrategy{ // Overide some methods
		defaults.NewBasicStrategy(), // Use defaults
	},
}

// Default Strategy for HyruleCastle
type DefaultHyruleCastleStrategy struct {
	// Inherit the basic create, delete, update strategy.
	defaults.BasicCreateDeleteUpdateStrategy
}

// NewFunc returns a new empty HyruleCastle
func (r DefaultHyruleCastleStrategy) NewFunc() runtime.Object {
	return &HyruleCastle{}
}

// NewListFunc returns a new empty List of HyruleCastle
func (r DefaultHyruleCastleStrategy) NewListFunc() runtime.Object {
	return &HyruleCastleList{}
}

// ObjectNameFunc returns the name for a HyruleCastle
func (r DefaultHyruleCastleStrategy) ObjectNameFunc(obj runtime.Object) (string, error) {
	return obj.(*HyruleCastle).Name, nil
}

func (HyruleCastleStrategy) PrepareForCreate(ctx genericapirequest.Context, obj runtime.Object) {
	o := obj.(*HyruleCastle)
	o.Status = HyruleCastleStatus{}
	o.Generation = 1
}

func (HyruleCastleStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, old runtime.Object) {
	newHyruleCastle := obj.(*HyruleCastle)
	oldHyruleCastle := old.(*HyruleCastle)
	newHyruleCastle.Status = oldHyruleCastle.Status

	// Spec and annotation updates bump the generation.
	if !reflect.DeepEqual(newHyruleCastle.Spec, oldHyruleCastle.Spec) ||
		!reflect.DeepEqual(newHyruleCastle.Annotations, oldHyruleCastle.Annotations) {
		newHyruleCastle.Generation = oldHyruleCastle.Generation + 1
	}
}

// Implement Status endpoint
// StatusREST implements the REST endpoint for changing the status of a deployment
type HyruleCastleStatusStrategy struct {
	HyruleCastleStrategy
}

// HyruleCastleStatusStrategySingleton contains the cross-cutting storage
var HyruleCastleStatusStrategySingleton = HyruleCastleStatusStrategy{*HyruleCastleStrategySingleton}

// PrepareForUpdate clears fields that are not allowed to be set by end users on update of status
func (HyruleCastleStatusStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, old runtime.Object) {
	newHyruleCastle := obj.(*HyruleCastle)
	oldHyruleCastle := old.(*HyruleCastle)
	newHyruleCastle.Spec = oldHyruleCastle.Spec
	newHyruleCastle.Labels = oldHyruleCastle.Labels
}

// Implement Registry
// storage puts strong typing around storage calls
type storageHyruleCastle struct {
	rest.StandardStorage
}

func (s *storageHyruleCastle) ListHyruleCastles(ctx genericapirequest.Context, options *metainternalversion.ListOptions) (*HyruleCastleList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	obj, err := s.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*HyruleCastleList), err
}

func (s *storageHyruleCastle) GetHyruleCastle(ctx genericapirequest.Context, id string, options *metav1.GetOptions) (*HyruleCastle, error) {
	obj, err := s.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*HyruleCastle), nil
}

func (s *storageHyruleCastle) CreateHyruleCastle(ctx genericapirequest.Context, object *HyruleCastle) (*HyruleCastle, error) {
	obj, err := s.Create(ctx, object)
	if err != nil {
		return nil, err
	}
	return obj.(*HyruleCastle), nil
}

func (s *storageHyruleCastle) UpdateHyruleCastle(ctx genericapirequest.Context, object *HyruleCastle) (*HyruleCastle, error) {
	obj, _, err := s.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object, api.Scheme))
	if err != nil {
		return nil, err
	}
	return obj.(*HyruleCastle), nil
}

func (s *storageHyruleCastle) DeleteHyruleCastle(ctx genericapirequest.Context, id string) error {
	_, err := s.Delete(ctx, id, nil)
	return err
}
